{
 "title": "Waku Node (all nodes)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Connected Peers #0",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "connected_peers{node=\"0\"}"
    }
   ]
  },
  {
   "title": "Valid Envelopes #0",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "valid_envelopes_total{node=\"0\"}"
    }
   ]
  },
  {
   "title": "Invalid Envelopes #0",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "dropped_expired_envelopes_total{node=\"0\"} + dropped_from_future_envelopes_total{node=\"0\"} + dropped_low_pow_envelopes_total{node=\"0\"} + dropped_too_large_envelopes_total{node=\"0\"} + dropped_bloom_filter_mismatch_envelopes_total{node=\"0\"} + dropped_topic_mismatch_envelopes_total{node=\"0\"} +dropped_benign_duplicate_envelopes_total{node=\"0\"} + dropped_duplicate_envelopes_total{node=\"0\"}",
     "legendFormat": "Invalid envelopes"
    }
   ]
  },
  {
   "title": "CPU Usage #0",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{node=\"0\"}[5s]) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "RSS Memory #0",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{node=\"0\"}"
    }
   ]
  },
  {
   "title": "Waku Envelopes #0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "valid_envelopes_total{node=\"0\"}",
     "legendFormat": "Valid"
    },
    {
     "expr": "dropped_benign_duplicate_envelopes_total{node=\"0\"}",
     "legendFormat": "Benign duplicate"
    },
    {
     "expr": "dropped_duplicate_envelopes_total{node=\"0\"}",
     "legendFormat": "Duplicate"
    },
    {
     "expr": "dropped_expired_envelopes_total{node=\"0\"}",
     "legendFormat": "Expired"
    },
    {
     "expr": "dropped_from_future_envelopes_total{node=\"0\"}",
     "legendFormat": "Future timestamped"
    },
    {
     "expr": "dropped_low_pow_envelopes_total{node=\"0\"}",
     "legendFormat": "Too low PoW"
    },
    {
     "expr": "dropped_bloom_filter_mismatch_envelopes_total{node=\"0\"}",
     "legendFormat": "Bloom filter mismatch"
    },
    {
     "expr": "dropped_topic_mismatch_envelopes_total{node=\"0\"}",
     "legendFormat": "Topic mismatch"
    },
    {
     "expr": "dropped_too_large_envelopes_total{node=\"0\"}",
     "legendFormat": "Too Large"
    },
    {
     "expr": "dropped_full_queue_new_envelopes_total{node=\"0\"}",
     "legendFormat": "Full queue new"
    },
    {
     "expr": "dropped_full_queue_old_envelopes_total{node=\"0\"}",
     "legendFormat": "Full queue old"
    }
   ]
  },
  {
   "title": "Waku Node #0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connected_peers{node=\"0\"}",
     "legendFormat": "Connected Peers"
    },
    {
     "expr": "process_resident_memory_bytes{node=\"0\"}",
     "legendFormat": "RSS Memory"
    },
    {
     "expr": "rate(process_cpu_seconds_total{node=\"0\"}[15s]) * 100",
     "legendFormat": "CPU usage %"
    }
   ]
  },
  {
   "title": "File Descriptors #0",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{node=\"0\"}",
     "legendFormat": "Maximum file descriptors"
    },
    {
     "expr": "process_open_fds{node=\"0\"}",
     "legendFormat": "Open file descriptors"
    }
   ]
  },
  {
   "title": "Memory Usage #0",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nim_gc_mem_bytes{node=\"0\"}",
     "legendFormat": "Nim GC total memory"
    },
    {
     "expr": "nim_gc_mem_occupied_bytes{node=\"0\"}",
     "legendFormat": "Nim GC used memory"
    },
    {
     "expr": "process_resident_memory_bytes{node=\"0\"}",
     "legendFormat": "RSS memory"
    },
    {
     "expr": "process_virtual_memory_bytes{node=\"0\"}",
     "legendFormat": "Virtual memory"
    }
   ]
  },
  {
   "title": "Connected Peers #1",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "connected_peers{node=\"1\"}"
    }
   ]
  },
  {
   "title": "Valid Envelopes #1",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "valid_envelopes_total{node=\"1\"}"
    }
   ]
  },
  {
   "title": "Invalid Envelopes #1",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "dropped_expired_envelopes_total{node=\"1\"} + dropped_from_future_envelopes_total{node=\"1\"} + dropped_low_pow_envelopes_total{node=\"1\"} + dropped_too_large_envelopes_total{node=\"1\"} + dropped_bloom_filter_mismatch_envelopes_total{node=\"1\"} + dropped_topic_mismatch_envelopes_total{node=\"1\"} +dropped_benign_duplicate_envelopes_total{node=\"1\"} + dropped_duplicate_envelopes_total{node=\"1\"}",
     "legendFormat": "Invalid envelopes"
    }
   ]
  },
  {
   "title": "CPU Usage #1",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 21 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{node=\"1\"}[5s]) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "RSS Memory #1",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 21 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{node=\"1\"}"
    }
   ]
  },
  {
   "title": "Waku Envelopes #1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "valid_envelopes_total{node=\"1\"}",
     "legendFormat": "Valid"
    },
    {
     "expr": "dropped_benign_duplicate_envelopes_total{node=\"1\"}",
     "legendFormat": "Benign duplicate"
    },
    {
     "expr": "dropped_duplicate_envelopes_total{node=\"1\"}",
     "legendFormat": "Duplicate"
    },
    {
     "expr": "dropped_expired_envelopes_total{node=\"1\"}",
     "legendFormat": "Expired"
    },
    {
     "expr": "dropped_from_future_envelopes_total{node=\"1\"}",
     "legendFormat": "Future timestamped"
    },
    {
     "expr": "dropped_low_pow_envelopes_total{node=\"1\"}",
     "legendFormat": "Too low PoW"
    },
    {
     "expr": "dropped_bloom_filter_mismatch_envelopes_total{node=\"1\"}",
     "legendFormat": "Bloom filter mismatch"
    },
    {
     "expr": "dropped_topic_mismatch_envelopes_total{node=\"1\"}",
     "legendFormat": "Topic mismatch"
    },
    {
     "expr": "dropped_too_large_envelopes_total{node=\"1\"}",
     "legendFormat": "Too Large"
    },
    {
     "expr": "dropped_full_queue_new_envelopes_total{node=\"1\"}",
     "legendFormat": "Full queue new"
    },
    {
     "expr": "dropped_full_queue_old_envelopes_total{node=\"1\"}",
     "legendFormat": "Full queue old"
    }
   ]
  },
  {
   "title": "Waku Node #1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connected_peers{node=\"1\"}",
     "legendFormat": "Connected Peers"
    },
    {
     "expr": "process_resident_memory_bytes{node=\"1\"}",
     "legendFormat": "RSS Memory"
    },
    {
     "expr": "rate(process_cpu_seconds_total{node=\"1\"}[15s]) * 100",
     "legendFormat": "CPU usage %"
    }
   ]
  },
  {
   "title": "File Descriptors #1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{node=\"1\"}",
     "legendFormat": "Maximum file descriptors"
    },
    {
     "expr": "process_open_fds{node=\"1\"}",
     "legendFormat": "Open file descriptors"
    }
   ]
  },
  {
   "title": "Memory Usage #1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nim_gc_mem_bytes{node=\"1\"}",
     "legendFormat": "Nim GC total memory"
    },
    {
     "expr": "nim_gc_mem_occupied_bytes{node=\"1\"}",
     "legendFormat": "Nim GC used memory"
    },
    {
     "expr": "process_resident_memory_bytes{node=\"1\"}",
     "legendFormat": "RSS memory"
    },
    {
     "expr": "process_virtual_memory_bytes{node=\"1\"}",
     "legendFormat": "Virtual memory"
    }
   ]
  },
  {
   "title": "Connected Peers #2",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "connected_peers{node=\"2\"}"
    }
   ]
  },
  {
   "title": "Valid Envelopes #2",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "valid_envelopes_total{node=\"2\"}"
    }
   ]
  },
  {
   "title": "Invalid Envelopes #2",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "dropped_expired_envelopes_total{node=\"2\"} + dropped_from_future_envelopes_total{node=\"2\"} + dropped_low_pow_envelopes_total{node=\"2\"} + dropped_too_large_envelopes_total{node=\"2\"} + dropped_bloom_filter_mismatch_envelopes_total{node=\"2\"} + dropped_topic_mismatch_envelopes_total{node=\"2\"} +dropped_benign_duplicate_envelopes_total{node=\"2\"} + dropped_duplicate_envelopes_total{node=\"2\"}",
     "legendFormat": "Invalid envelopes"
    }
   ]
  },
  {
   "title": "CPU Usage #2",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 42 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{node=\"2\"}[5s]) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "RSS Memory #2",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 42 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{node=\"2\"}"
    }
   ]
  },
  {
   "title": "Waku Envelopes #2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "valid_envelopes_total{node=\"2\"}",
     "legendFormat": "Valid"
    },
    {
     "expr": "dropped_benign_duplicate_envelopes_total{node=\"2\"}",
     "legendFormat": "Benign duplicate"
    },
    {
     "expr": "dropped_duplicate_envelopes_total{node=\"2\"}",
     "legendFormat": "Duplicate"
    },
    {
     "expr": "dropped_expired_envelopes_total{node=\"2\"}",
     "legendFormat": "Expired"
    },
    {
     "expr": "dropped_from_future_envelopes_total{node=\"2\"}",
     "legendFormat": "Future timestamped"
    },
    {
     "expr": "dropped_low_pow_envelopes_total{node=\"2\"}",
     "legendFormat": "Too low PoW"
    },
    {
     "expr": "dropped_bloom_filter_mismatch_envelopes_total{node=\"2\"}",
     "legendFormat": "Bloom filter mismatch"
    },
    {
     "expr": "dropped_topic_mismatch_envelopes_total{node=\"2\"}",
     "legendFormat": "Topic mismatch"
    },
    {
     "expr": "dropped_too_large_envelopes_total{node=\"2\"}",
     "legendFormat": "Too Large"
    },
    {
     "expr": "dropped_full_queue_new_envelopes_total{node=\"2\"}",
     "legendFormat": "Full queue new"
    },
    {
     "expr": "dropped_full_queue_old_envelopes_total{node=\"2\"}",
     "legendFormat": "Full queue old"
    }
   ]
  },
  {
   "title": "Waku Node #2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connected_peers{node=\"2\"}",
     "legendFormat": "Connected Peers"
    },
    {
     "expr": "process_resident_memory_bytes{node=\"2\"}",
     "legendFormat": "RSS Memory"
    },
    {
     "expr": "rate(process_cpu_seconds_total{node=\"2\"}[15s]) * 100",
     "legendFormat": "CPU usage %"
    }
   ]
  },
  {
   "title": "File Descriptors #2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{node=\"2\"}",
     "legendFormat": "Maximum file descriptors"
    },
    {
     "expr": "process_open_fds{node=\"2\"}",
     "legendFormat": "Open file descriptors"
    }
   ]
  },
  {
   "title": "Memory Usage #2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nim_gc_mem_bytes{node=\"2\"}",
     "legendFormat": "Nim GC total memory"
    },
    {
     "expr": "nim_gc_mem_occupied_bytes{node=\"2\"}",
     "legendFormat": "Nim GC used memory"
    },
    {
     "expr": "process_resident_memory_bytes{node=\"2\"}",
     "legendFormat": "RSS memory"
    },
    {
     "expr": "process_virtual_memory_bytes{node=\"2\"}",
     "legendFormat": "Virtual memory"
    }
   ]
  },
  {
   "title": "Connected Peers #3",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "connected_peers{node=\"3\"}"
    }
   ]
  },
  {
   "title": "Valid Envelopes #3",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 63 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "valid_envelopes_total{node=\"3\"}"
    }
   ]
  },
  {
   "title": "Invalid Envelopes #3",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 63 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "dropped_expired_envelopes_total{node=\"3\"} + dropped_from_future_envelopes_total{node=\"3\"} + dropped_low_pow_envelopes_total{node=\"3\"} + dropped_too_large_envelopes_total{node=\"3\"} + dropped_bloom_filter_mismatch_envelopes_total{node=\"3\"} + dropped_topic_mismatch_envelopes_total{node=\"3\"} +dropped_benign_duplicate_envelopes_total{node=\"3\"} + dropped_duplicate_envelopes_total{node=\"3\"}",
     "legendFormat": "Invalid envelopes"
    }
   ]
  },
  {
   "title": "CPU Usage #3",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 63 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{node=\"3\"}[5s]) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "RSS Memory #3",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 63 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{node=\"3\"}"
    }
   ]
  },
  {
   "title": "Waku Envelopes #3",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "valid_envelopes_total{node=\"3\"}",
     "legendFormat": "Valid"
    },
    {
     "expr": "dropped_benign_duplicate_envelopes_total{node=\"3\"}",
     "legendFormat": "Benign duplicate"
    },
    {
     "expr": "dropped_duplicate_envelopes_total{node=\"3\"}",
     "legendFormat": "Duplicate"
    },
    {
     "expr": "dropped_expired_envelopes_total{node=\"3\"}",
     "legendFormat": "Expired"
    },
    {
     "expr": "dropped_from_future_envelopes_total{node=\"3\"}",
     "legendFormat": "Future timestamped"
    },
    {
     "expr": "dropped_low_pow_envelopes_total{node=\"3\"}",
     "legendFormat": "Too low PoW"
    },
    {
     "expr": "dropped_bloom_filter_mismatch_envelopes_total{node=\"3\"}",
     "legendFormat": "Bloom filter mismatch"
    },
    {
     "expr": "dropped_topic_mismatch_envelopes_total{node=\"3\"}",
     "legendFormat": "Topic mismatch"
    },
    {
     "expr": "dropped_too_large_envelopes_total{node=\"3\"}",
     "legendFormat": "Too Large"
    },
    {
     "expr": "dropped_full_queue_new_envelopes_total{node=\"3\"}",
     "legendFormat": "Full queue new"
    },
    {
     "expr": "dropped_full_queue_old_envelopes_total{node=\"3\"}",
     "legendFormat": "Full queue old"
    }
   ]
  },
  {
   "title": "Waku Node #3",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connected_peers{node=\"3\"}",
     "legendFormat": "Connected Peers"
    },
    {
     "expr": "process_resident_memory_bytes{node=\"3\"}",
     "legendFormat": "RSS Memory"
    },
    {
     "expr": "rate(process_cpu_seconds_total{node=\"3\"}[15s]) * 100",
     "legendFormat": "CPU usage %"
    }
   ]
  },
  {
   "title": "File Descriptors #3",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{node=\"3\"}",
     "legendFormat": "Maximum file descriptors"
    },
    {
     "expr": "process_open_fds{node=\"3\"}",
     "legendFormat": "Open file descriptors"
    }
   ]
  },
  {
   "title": "Memory Usage #3",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nim_gc_mem_bytes{node=\"3\"}",
     "legendFormat": "Nim GC total memory"
    },
    {
     "expr": "nim_gc_mem_occupied_bytes{node=\"3\"}",
     "legendFormat": "Nim GC used memory"
    },
    {
     "expr": "process_resident_memory_bytes{node=\"3\"}",
     "legendFormat": "RSS memory"
    },
    {
     "expr": "process_virtual_memory_bytes{node=\"3\"}",
     "legendFormat": "Virtual memory"
    }
   ]
  },
  {
   "title": "Connected Peers #4",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "connected_peers{node=\"4\"}"
    }
   ]
  },
  {
   "title": "Valid Envelopes #4",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 84 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "valid_envelopes_total{node=\"4\"}"
    }
   ]
  },
  {
   "title": "Invalid Envelopes #4",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 84 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "dropped_expired_envelopes_total{node=\"4\"} + dropped_from_future_envelopes_total{node=\"4\"} + dropped_low_pow_envelopes_total{node=\"4\"} + dropped_too_large_envelopes_total{node=\"4\"} + dropped_bloom_filter_mismatch_envelopes_total{node=\"4\"} + dropped_topic_mismatch_envelopes_total{node=\"4\"} +dropped_benign_duplicate_envelopes_total{node=\"4\"} + dropped_duplicate_envelopes_total{node=\"4\"}",
     "legendFormat": "Invalid envelopes"
    }
   ]
  },
  {
   "title": "CPU Usage #4",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 84 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{node=\"4\"}[5s]) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "RSS Memory #4",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 84 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{node=\"4\"}"
    }
   ]
  },
  {
   "title": "Waku Envelopes #4",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "valid_envelopes_total{node=\"4\"}",
     "legendFormat": "Valid"
    },
    {
     "expr": "dropped_benign_duplicate_envelopes_total{node=\"4\"}",
     "legendFormat": "Benign duplicate"
    },
    {
     "expr": "dropped_duplicate_envelopes_total{node=\"4\"}",
     "legendFormat": "Duplicate"
    },
    {
     "expr": "dropped_expired_envelopes_total{node=\"4\"}",
     "legendFormat": "Expired"
    },
    {
     "expr": "dropped_from_future_envelopes_total{node=\"4\"}",
     "legendFormat": "Future timestamped"
    },
    {
     "expr": "dropped_low_pow_envelopes_total{node=\"4\"}",
     "legendFormat": "Too low PoW"
    },
    {
     "expr": "dropped_bloom_filter_mismatch_envelopes_total{node=\"4\"}",
     "legendFormat": "Bloom filter mismatch"
    },
    {
     "expr": "dropped_topic_mismatch_envelopes_total{node=\"4\"}",
     "legendFormat": "Topic mismatch"
    },
    {
     "expr": "dropped_too_large_envelopes_total{node=\"4\"}",
     "legendFormat": "Too Large"
    },
    {
     "expr": "dropped_full_queue_new_envelopes_total{node=\"4\"}",
     "legendFormat": "Full queue new"
    },
    {
     "expr": "dropped_full_queue_old_envelopes_total{node=\"4\"}",
     "legendFormat": "Full queue old"
    }
   ]
  },
  {
   "title": "Waku Node #4",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connected_peers{node=\"4\"}",
     "legendFormat": "Connected Peers"
    },
    {
     "expr": "process_resident_memory_bytes{node=\"4\"}",
     "legendFormat": "RSS Memory"
    },
    {
     "expr": "rate(process_cpu_seconds_total{node=\"4\"}[15s]) * 100",
     "legendFormat": "CPU usage %"
    }
   ]
  },
  {
   "title": "File Descriptors #4",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{node=\"4\"}",
     "legendFormat": "Maximum file descriptors"
    },
    {
     "expr": "process_open_fds{node=\"4\"}",
     "legendFormat": "Open file descriptors"
    }
   ]
  },
  {
   "title": "Memory Usage #4",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nim_gc_mem_bytes{node=\"4\"}",
     "legendFormat": "Nim GC total memory"
    },
    {
     "expr": "nim_gc_mem_occupied_bytes{node=\"4\"}",
     "legendFormat": "Nim GC used memory"
    },
    {
     "expr": "process_resident_memory_bytes{node=\"4\"}",
     "legendFormat": "RSS memory"
    },
    {
     "expr": "process_virtual_memory_bytes{node=\"4\"}",
     "legendFormat": "Virtual memory"
    }
   ]
  },
  {
   "title": "Connected Peers #5",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 105 },
   "targets": [
    {
     "expr": "connected_peers{node=\"5\"}"
    }
   ]
  },
  {
   "title": "Valid Envelopes #5",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 105 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "valid_envelopes_total{node=\"5\"}"
    }
   ]
  },
  {
   "title": "Invalid Envelopes #5",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 105 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "dropped_expired_envelopes_total{node=\"5\"} + dropped_from_future_envelopes_total{node=\"5\"} + dropped_low_pow_envelopes_total{node=\"5\"} + dropped_too_large_envelopes_total{node=\"5\"} + dropped_bloom_filter_mismatch_envelopes_total{node=\"5\"} + dropped_topic_mismatch_envelopes_total{node=\"5\"} +dropped_benign_duplicate_envelopes_total{node=\"5\"} + dropped_duplicate_envelopes_total{node=\"5\"}",
     "legendFormat": "Invalid envelopes"
    }
   ]
  },
  {
   "title": "CPU Usage #5",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 105 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{node=\"5\"}[5s]) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "RSS Memory #5",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 105 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{node=\"5\"}"
    }
   ]
  },
  {
   "title": "Waku Envelopes #5",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "valid_envelopes_total{node=\"5\"}",
     "legendFormat": "Valid"
    },
    {
     "expr": "dropped_benign_duplicate_envelopes_total{node=\"5\"}",
     "legendFormat": "Benign duplicate"
    },
    {
     "expr": "dropped_duplicate_envelopes_total{node=\"5\"}",
     "legendFormat": "Duplicate"
    },
    {
     "expr": "dropped_expired_envelopes_total{node=\"5\"}",
     "legendFormat": "Expired"
    },
    {
     "expr": "dropped_from_future_envelopes_total{node=\"5\"}",
     "legendFormat": "Future timestamped"
    },
    {
     "expr": "dropped_low_pow_envelopes_total{node=\"5\"}",
     "legendFormat": "Too low PoW"
    },
    {
     "expr": "dropped_bloom_filter_mismatch_envelopes_total{node=\"5\"}",
     "legendFormat": "Bloom filter mismatch"
    },
    {
     "expr": "dropped_topic_mismatch_envelopes_total{node=\"5\"}",
     "legendFormat": "Topic mismatch"
    },
    {
     "expr": "dropped_too_large_envelopes_total{node=\"5\"}",
     "legendFormat": "Too Large"
    },
    {
     "expr": "dropped_full_queue_new_envelopes_total{node=\"5\"}",
     "legendFormat": "Full queue new"
    },
    {
     "expr": "dropped_full_queue_old_envelopes_total{node=\"5\"}",
     "legendFormat": "Full queue old"
    }
   ]
  },
  {
   "title": "Waku Node #5",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connected_peers{node=\"5\"}",
     "legendFormat": "Connected Peers"
    },
    {
     "expr": "process_resident_memory_bytes{node=\"5\"}",
     "legendFormat": "RSS Memory"
    },
    {
     "expr": "rate(process_cpu_seconds_total{node=\"5\"}[15s]) * 100",
     "legendFormat": "CPU usage %"
    }
   ]
  },
  {
   "title": "File Descriptors #5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{node=\"5\"}",
     "legendFormat": "Maximum file descriptors"
    },
    {
     "expr": "process_open_fds{node=\"5\"}",
     "legendFormat": "Open file descriptors"
    }
   ]
  },
  {
   "title": "Memory Usage #5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nim_gc_mem_bytes{node=\"5\"}",
     "legendFormat": "Nim GC total memory"
    },
    {
     "expr": "nim_gc_mem_occupied_bytes{node=\"5\"}",
     "legendFormat": "Nim GC used memory"
    },
    {
     "expr": "process_resident_memory_bytes{node=\"5\"}",
     "legendFormat": "RSS memory"
    },
    {
     "expr": "process_virtual_memory_bytes{node=\"5\"}",
     "legendFormat": "Virtual memory"
    }
   ]
  },
  {
   "title": "Connected Peers #6",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 126 },
   "targets": [
    {
     "expr": "connected_peers{node=\"6\"}"
    }
   ]
  },
  {
   "title": "Valid Envelopes #6",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 126 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "valid_envelopes_total{node=\"6\"}"
    }
   ]
  },
  {
   "title": "Invalid Envelopes #6",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 126 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "dropped_expired_envelopes_total{node=\"6\"} + dropped_from_future_envelopes_total{node=\"6\"} + dropped_low_pow_envelopes_total{node=\"6\"} + dropped_too_large_envelopes_total{node=\"6\"} + dropped_bloom_filter_mismatch_envelopes_total{node=\"6\"} + dropped_topic_mismatch_envelopes_total{node=\"6\"} +dropped_benign_duplicate_envelopes_total{node=\"6\"} + dropped_duplicate_envelopes_total{node=\"6\"}",
     "legendFormat": "Invalid envelopes"
    }
   ]
  },
  {
   "title": "CPU Usage #6",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 126 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{node=\"6\"}[5s]) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "RSS Memory #6",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 126 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{node=\"6\"}"
    }
   ]
  },
  {
   "title": "Waku Envelopes #6",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "valid_envelopes_total{node=\"6\"}",
     "legendFormat": "Valid"
    },
    {
     "expr": "dropped_benign_duplicate_envelopes_total{node=\"6\"}",
     "legendFormat": "Benign duplicate"
    },
    {
     "expr": "dropped_duplicate_envelopes_total{node=\"6\"}",
     "legendFormat": "Duplicate"
    },
    {
     "expr": "dropped_expired_envelopes_total{node=\"6\"}",
     "legendFormat": "Expired"
    },
    {
     "expr": "dropped_from_future_envelopes_total{node=\"6\"}",
     "legendFormat": "Future timestamped"
    },
    {
     "expr": "dropped_low_pow_envelopes_total{node=\"6\"}",
     "legendFormat": "Too low PoW"
    },
    {
     "expr": "dropped_bloom_filter_mismatch_envelopes_total{node=\"6\"}",
     "legendFormat": "Bloom filter mismatch"
    },
    {
     "expr": "dropped_topic_mismatch_envelopes_total{node=\"6\"}",
     "legendFormat": "Topic mismatch"
    },
    {
     "expr": "dropped_too_large_envelopes_total{node=\"6\"}",
     "legendFormat": "Too Large"
    },
    {
     "expr": "dropped_full_queue_new_envelopes_total{node=\"6\"}",
     "legendFormat": "Full queue new"
    },
    {
     "expr": "dropped_full_queue_old_envelopes_total{node=\"6\"}",
     "legendFormat": "Full queue old"
    }
   ]
  },
  {
   "title": "Waku Node #6",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 130 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connected_peers{node=\"6\"}",
     "legendFormat": "Connected Peers"
    },
    {
     "expr": "process_resident_memory_bytes{node=\"6\"}",
     "legendFormat": "RSS Memory"
    },
    {
     "expr": "rate(process_cpu_seconds_total{node=\"6\"}[15s]) * 100",
     "legendFormat": "CPU usage %"
    }
   ]
  },
  {
   "title": "File Descriptors #6",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{node=\"6\"}",
     "legendFormat": "Maximum file descriptors"
    },
    {
     "expr": "process_open_fds{node=\"6\"}",
     "legendFormat": "Open file descriptors"
    }
   ]
  },
  {
   "title": "Memory Usage #6",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 139 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nim_gc_mem_bytes{node=\"6\"}",
     "legendFormat": "Nim GC total memory"
    },
    {
     "expr": "nim_gc_mem_occupied_bytes{node=\"6\"}",
     "legendFormat": "Nim GC used memory"
    },
    {
     "expr": "process_resident_memory_bytes{node=\"6\"}",
     "legendFormat": "RSS memory"
    },
    {
     "expr": "process_virtual_memory_bytes{node=\"6\"}",
     "legendFormat": "Virtual memory"
    }
   ]
  },
  {
   "title": "Connected Peers #7",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 147 },
   "targets": [
    {
     "expr": "connected_peers{node=\"7\"}"
    }
   ]
  },
  {
   "title": "Valid Envelopes #7",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 147 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "valid_envelopes_total{node=\"7\"}"
    }
   ]
  },
  {
   "title": "Invalid Envelopes #7",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 147 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "dropped_expired_envelopes_total{node=\"7\"} + dropped_from_future_envelopes_total{node=\"7\"} + dropped_low_pow_envelopes_total{node=\"7\"} + dropped_too_large_envelopes_total{node=\"7\"} + dropped_bloom_filter_mismatch_envelopes_total{node=\"7\"} + dropped_topic_mismatch_envelopes_total{node=\"7\"} +dropped_benign_duplicate_envelopes_total{node=\"7\"} + dropped_duplicate_envelopes_total{node=\"7\"}",
     "legendFormat": "Invalid envelopes"
    }
   ]
  },
  {
   "title": "CPU Usage #7",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 147 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{node=\"7\"}[5s]) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "RSS Memory #7",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 147 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{node=\"7\"}"
    }
   ]
  },
  {
   "title": "Waku Envelopes #7",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 151 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "valid_envelopes_total{node=\"7\"}",
     "legendFormat": "Valid"
    },
    {
     "expr": "dropped_benign_duplicate_envelopes_total{node=\"7\"}",
     "legendFormat": "Benign duplicate"
    },
    {
     "expr": "dropped_duplicate_envelopes_total{node=\"7\"}",
     "legendFormat": "Duplicate"
    },
    {
     "expr": "dropped_expired_envelopes_total{node=\"7\"}",
     "legendFormat": "Expired"
    },
    {
     "expr": "dropped_from_future_envelopes_total{node=\"7\"}",
     "legendFormat": "Future timestamped"
    },
    {
     "expr": "dropped_low_pow_envelopes_total{node=\"7\"}",
     "legendFormat": "Too low PoW"
    },
    {
     "expr": "dropped_bloom_filter_mismatch_envelopes_total{node=\"7\"}",
     "legendFormat": "Bloom filter mismatch"
    },
    {
     "expr": "dropped_topic_mismatch_envelopes_total{node=\"7\"}",
     "legendFormat": "Topic mismatch"
    },
    {
     "expr": "dropped_too_large_envelopes_total{node=\"7\"}",
     "legendFormat": "Too Large"
    },
    {
     "expr": "dropped_full_queue_new_envelopes_total{node=\"7\"}",
     "legendFormat": "Full queue new"
    },
    {
     "expr": "dropped_full_queue_old_envelopes_total{node=\"7\"}",
     "legendFormat": "Full queue old"
    }
   ]
  },
  {
   "title": "Waku Node #7",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 151 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connected_peers{node=\"7\"}",
     "legendFormat": "Connected Peers"
    },
    {
     "expr": "process_resident_memory_bytes{node=\"7\"}",
     "legendFormat": "RSS Memory"
    },
    {
     "expr": "rate(process_cpu_seconds_total{node=\"7\"}[15s]) * 100",
     "legendFormat": "CPU usage %"
    }
   ]
  },
  {
   "title": "File Descriptors #7",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{node=\"7\"}",
     "legendFormat": "Maximum file descriptors"
    },
    {
     "expr": "process_open_fds{node=\"7\"}",
     "legendFormat": "Open file descriptors"
    }
   ]
  },
  {
   "title": "Memory Usage #7",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 160 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nim_gc_mem_bytes{node=\"7\"}",
     "legendFormat": "Nim GC total memory"
    },
    {
     "expr": "nim_gc_mem_occupied_bytes{node=\"7\"}",
     "legendFormat": "Nim GC used memory"
    },
    {
     "expr": "process_resident_memory_bytes{node=\"7\"}",
     "legendFormat": "RSS memory"
    },
    {
     "expr": "process_virtual_memory_bytes{node=\"7\"}",
     "legendFormat": "Virtual memory"
    }
   ]
  },
  {
   "title": "Connected Peers #8",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 168 },
   "targets": [
    {
     "expr": "connected_peers{node=\"8\"}"
    }
   ]
  },
  {
   "title": "Valid Envelopes #8",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 168 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "valid_envelopes_total{node=\"8\"}"
    }
   ]
  },
  {
   "title": "Invalid Envelopes #8",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 168 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "dropped_expired_envelopes_total{node=\"8\"} + dropped_from_future_envelopes_total{node=\"8\"} + dropped_low_pow_envelopes_total{node=\"8\"} + dropped_too_large_envelopes_total{node=\"8\"} + dropped_bloom_filter_mismatch_envelopes_total{node=\"8\"} + dropped_topic_mismatch_envelopes_total{node=\"8\"} +dropped_benign_duplicate_envelopes_total{node=\"8\"} + dropped_duplicate_envelopes_total{node=\"8\"}",
     "legendFormat": "Invalid envelopes"
    }
   ]
  },
  {
   "title": "CPU Usage #8",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 168 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{node=\"8\"}[5s]) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "RSS Memory #8",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 168 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{node=\"8\"}"
    }
   ]
  },
  {
   "title": "Waku Envelopes #8",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 172 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "valid_envelopes_total{node=\"8\"}",
     "legendFormat": "Valid"
    },
    {
     "expr": "dropped_benign_duplicate_envelopes_total{node=\"8\"}",
     "legendFormat": "Benign duplicate"
    },
    {
     "expr": "dropped_duplicate_envelopes_total{node=\"8\"}",
     "legendFormat": "Duplicate"
    },
    {
     "expr": "dropped_expired_envelopes_total{node=\"8\"}",
     "legendFormat": "Expired"
    },
    {
     "expr": "dropped_from_future_envelopes_total{node=\"8\"}",
     "legendFormat": "Future timestamped"
    },
    {
     "expr": "dropped_low_pow_envelopes_total{node=\"8\"}",
     "legendFormat": "Too low PoW"
    },
    {
     "expr": "dropped_bloom_filter_mismatch_envelopes_total{node=\"8\"}",
     "legendFormat": "Bloom filter mismatch"
    },
    {
     "expr": "dropped_topic_mismatch_envelopes_total{node=\"8\"}",
     "legendFormat": "Topic mismatch"
    },
    {
     "expr": "dropped_too_large_envelopes_total{node=\"8\"}",
     "legendFormat": "Too Large"
    },
    {
     "expr": "dropped_full_queue_new_envelopes_total{node=\"8\"}",
     "legendFormat": "Full queue new"
    },
    {
     "expr": "dropped_full_queue_old_envelopes_total{node=\"8\"}",
     "legendFormat": "Full queue old"
    }
   ]
  },
  {
   "title": "Waku Node #8",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 172 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connected_peers{node=\"8\"}",
     "legendFormat": "Connected Peers"
    },
    {
     "expr": "process_resident_memory_bytes{node=\"8\"}",
     "legendFormat": "RSS Memory"
    },
    {
     "expr": "rate(process_cpu_seconds_total{node=\"8\"}[15s]) * 100",
     "legendFormat": "CPU usage %"
    }
   ]
  },
  {
   "title": "File Descriptors #8",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 181 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{node=\"8\"}",
     "legendFormat": "Maximum file descriptors"
    },
    {
     "expr": "process_open_fds{node=\"8\"}",
     "legendFormat": "Open file descriptors"
    }
   ]
  },
  {
   "title": "Memory Usage #8",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 181 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nim_gc_mem_bytes{node=\"8\"}",
     "legendFormat": "Nim GC total memory"
    },
    {
     "expr": "nim_gc_mem_occupied_bytes{node=\"8\"}",
     "legendFormat": "Nim GC used memory"
    },
    {
     "expr": "process_resident_memory_bytes{node=\"8\"}",
     "legendFormat": "RSS memory"
    },
    {
     "expr": "process_virtual_memory_bytes{node=\"8\"}",
     "legendFormat": "Virtual memory"
    }
   ]
  },
  {
   "title": "Connected Peers #9",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 189 },
   "targets": [
    {
     "expr": "connected_peers{node=\"9\"}"
    }
   ]
  },
  {
   "title": "Valid Envelopes #9",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 189 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "valid_envelopes_total{node=\"9\"}"
    }
   ]
  },
  {
   "title": "Invalid Envelopes #9",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 189 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "dropped_expired_envelopes_total{node=\"9\"} + dropped_from_future_envelopes_total{node=\"9\"} + dropped_low_pow_envelopes_total{node=\"9\"} + dropped_too_large_envelopes_total{node=\"9\"} + dropped_bloom_filter_mismatch_envelopes_total{node=\"9\"} + dropped_topic_mismatch_envelopes_total{node=\"9\"} +dropped_benign_duplicate_envelopes_total{node=\"9\"} + dropped_duplicate_envelopes_total{node=\"9\"}",
     "legendFormat": "Invalid envelopes"
    }
   ]
  },
  {
   "title": "CPU Usage #9",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 189 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{node=\"9\"}[5s]) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "RSS Memory #9",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 189 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{node=\"9\"}"
    }
   ]
  },
  {
   "title": "Waku Envelopes #9",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 193 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "valid_envelopes_total{node=\"9\"}",
     "legendFormat": "Valid"
    },
    {
     "expr": "dropped_benign_duplicate_envelopes_total{node=\"9\"}",
     "legendFormat": "Benign duplicate"
    },
    {
     "expr": "dropped_duplicate_envelopes_total{node=\"9\"}",
     "legendFormat": "Duplicate"
    },
    {
     "expr": "dropped_expired_envelopes_total{node=\"9\"}",
     "legendFormat": "Expired"
    },
    {
     "expr": "dropped_from_future_envelopes_total{node=\"9\"}",
     "legendFormat": "Future timestamped"
    },
    {
     "expr": "dropped_low_pow_envelopes_total{node=\"9\"}",
     "legendFormat": "Too low PoW"
    },
    {
     "expr": "dropped_bloom_filter_mismatch_envelopes_total{node=\"9\"}",
     "legendFormat": "Bloom filter mismatch"
    },
    {
     "expr": "dropped_topic_mismatch_envelopes_total{node=\"9\"}",
     "legendFormat": "Topic mismatch"
    },
    {
     "expr": "dropped_too_large_envelopes_total{node=\"9\"}",
     "legendFormat": "Too Large"
    },
    {
     "expr": "dropped_full_queue_new_envelopes_total{node=\"9\"}",
     "legendFormat": "Full queue new"
    },
    {
     "expr": "dropped_full_queue_old_envelopes_total{node=\"9\"}",
     "legendFormat": "Full queue old"
    }
   ]
  },
  {
   "title": "Waku Node #9",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 193 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connected_peers{node=\"9\"}",
     "legendFormat": "Connected Peers"
    },
    {
     "expr": "process_resident_memory_bytes{node=\"9\"}",
     "legendFormat": "RSS Memory"
    },
    {
     "expr": "rate(process_cpu_seconds_total{node=\"9\"}[15s]) * 100",
     "legendFormat": "CPU usage %"
    }
   ]
  },
  {
   "title": "File Descriptors #9",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 202 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{node=\"9\"}",
     "legendFormat": "Maximum file descriptors"
    },
    {
     "expr": "process_open_fds{node=\"9\"}",
     "legendFormat": "Open file descriptors"
    }
   ]
  },
  {
   "title": "Memory Usage #9",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 202 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nim_gc_mem_bytes{node=\"9\"}",
     "legendFormat": "Nim GC total memory"
    },
    {
     "expr": "nim_gc_mem_occupied_bytes{node=\"9\"}",
     "legendFormat": "Nim GC used memory"
    },
    {
     "expr": "process_resident_memory_bytes{node=\"9\"}",
     "legendFormat": "RSS memory"
    },
    {
     "expr": "process_virtual_memory_bytes{node=\"9\"}",
     "legendFormat": "Virtual memory"
    }
   ]
  },
  {
   "title": "Connected Peers #10",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 210 },
   "targets": [
    {
     "expr": "connected_peers{node=\"10\"}"
    }
   ]
  },
  {
   "title": "Valid Envelopes #10",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 210 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "valid_envelopes_total{node=\"10\"}"
    }
   ]
  },
  {
   "title": "Invalid Envelopes #10",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 210 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "dropped_expired_envelopes_total{node=\"10\"} + dropped_from_future_envelopes_total{node=\"10\"} + dropped_low_pow_envelopes_total{node=\"10\"} + dropped_too_large_envelopes_total{node=\"10\"} + dropped_bloom_filter_mismatch_envelopes_total{node=\"10\"} + dropped_topic_mismatch_envelopes_total{node=\"10\"} +dropped_benign_duplicate_envelopes_total{node=\"10\"} + dropped_duplicate_envelopes_total{node=\"10\"}",
     "legendFormat": "Invalid envelopes"
    }
   ]
  },
  {
   "title": "CPU Usage #10",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 210 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{node=\"10\"}[5s]) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "RSS Memory #10",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 210 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{node=\"10\"}"
    }
   ]
  },
  {
   "title": "Waku Envelopes #10",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 214 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "valid_envelopes_total{node=\"10\"}",
     "legendFormat": "Valid"
    },
    {
     "expr": "dropped_benign_duplicate_envelopes_total{node=\"10\"}",
     "legendFormat": "Benign duplicate"
    },
    {
     "expr": "dropped_duplicate_envelopes_total{node=\"10\"}",
     "legendFormat": "Duplicate"
    },
    {
     "expr": "dropped_expired_envelopes_total{node=\"10\"}",
     "legendFormat": "Expired"
    },
    {
     "expr": "dropped_from_future_envelopes_total{node=\"10\"}",
     "legendFormat": "Future timestamped"
    },
    {
     "expr": "dropped_low_pow_envelopes_total{node=\"10\"}",
     "legendFormat": "Too low PoW"
    },
    {
     "expr": "dropped_bloom_filter_mismatch_envelopes_total{node=\"10\"}",
     "legendFormat": "Bloom filter mismatch"
    },
    {
     "expr": "dropped_topic_mismatch_envelopes_total{node=\"10\"}",
     "legendFormat": "Topic mismatch"
    },
    {
     "expr": "dropped_too_large_envelopes_total{node=\"10\"}",
     "legendFormat": "Too Large"
    },
    {
     "expr": "dropped_full_queue_new_envelopes_total{node=\"10\"}",
     "legendFormat": "Full queue new"
    },
    {
     "expr": "dropped_full_queue_old_envelopes_total{node=\"10\"}",
     "legendFormat": "Full queue old"
    }
   ]
  },
  {
   "title": "Waku Node #10",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 214 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connected_peers{node=\"10\"}",
     "legendFormat": "Connected Peers"
    },
    {
     "expr": "process_resident_memory_bytes{node=\"10\"}",
     "legendFormat": "RSS Memory"
    },
    {
     "expr": "rate(process_cpu_seconds_total{node=\"10\"}[15s]) * 100",
     "legendFormat": "CPU usage %"
    }
   ]
  },
  {
   "title": "File Descriptors #10",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 223 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{node=\"10\"}",
     "legendFormat": "Maximum file descriptors"
    },
    {
     "expr": "process_open_fds{node=\"10\"}",
     "legendFormat": "Open file descriptors"
    }
   ]
  },
  {
   "title": "Memory Usage #10",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 223 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nim_gc_mem_bytes{node=\"10\"}",
     "legendFormat": "Nim GC total memory"
    },
    {
     "expr": "nim_gc_mem_occupied_bytes{node=\"10\"}",
     "legendFormat": "Nim GC used memory"
    },
    {
     "expr": "process_resident_memory_bytes{node=\"10\"}",
     "legendFormat": "RSS memory"
    },
    {
     "expr": "process_virtual_memory_bytes{node=\"10\"}",
     "legendFormat": "Virtual memory"
    }
   ]
  },
  {
   "title": "Connected Peers #11",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 231 },
   "targets": [
    {
     "expr": "connected_peers{node=\"11\"}"
    }
   ]
  },
  {
   "title": "Valid Envelopes #11",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 231 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "valid_envelopes_total{node=\"11\"}"
    }
   ]
  },
  {
   "title": "Invalid Envelopes #11",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 231 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "dropped_expired_envelopes_total{node=\"11\"} + dropped_from_future_envelopes_total{node=\"11\"} + dropped_low_pow_envelopes_total{node=\"11\"} + dropped_too_large_envelopes_total{node=\"11\"} + dropped_bloom_filter_mismatch_envelopes_total{node=\"11\"} + dropped_topic_mismatch_envelopes_total{node=\"11\"} +dropped_benign_duplicate_envelopes_total{node=\"11\"} + dropped_duplicate_envelopes_total{node=\"11\"}",
     "legendFormat": "Invalid envelopes"
    }
   ]
  },
  {
   "title": "CPU Usage #11",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 231 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{node=\"11\"}[5s]) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "RSS Memory #11",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 231 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{node=\"11\"}"
    }
   ]
  },
  {
   "title": "Waku Envelopes #11",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 235 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "valid_envelopes_total{node=\"11\"}",
     "legendFormat": "Valid"
    },
    {
     "expr": "dropped_benign_duplicate_envelopes_total{node=\"11\"}",
     "legendFormat": "Benign duplicate"
    },
    {
     "expr": "dropped_duplicate_envelopes_total{node=\"11\"}",
     "legendFormat": "Duplicate"
    },
    {
     "expr": "dropped_expired_envelopes_total{node=\"11\"}",
     "legendFormat": "Expired"
    },
    {
     "expr": "dropped_from_future_envelopes_total{node=\"11\"}",
     "legendFormat": "Future timestamped"
    },
    {
     "expr": "dropped_low_pow_envelopes_total{node=\"11\"}",
     "legendFormat": "Too low PoW"
    },
    {
     "expr": "dropped_bloom_filter_mismatch_envelopes_total{node=\"11\"}",
     "legendFormat": "Bloom filter mismatch"
    },
    {
     "expr": "dropped_topic_mismatch_envelopes_total{node=\"11\"}",
     "legendFormat": "Topic mismatch"
    },
    {
     "expr": "dropped_too_large_envelopes_total{node=\"11\"}",
     "legendFormat": "Too Large"
    },
    {
     "expr": "dropped_full_queue_new_envelopes_total{node=\"11\"}",
     "legendFormat": "Full queue new"
    },
    {
     "expr": "dropped_full_queue_old_envelopes_total{node=\"11\"}",
     "legendFormat": "Full queue old"
    }
   ]
  },
  {
   "title": "Waku Node #11",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 235 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connected_peers{node=\"11\"}",
     "legendFormat": "Connected Peers"
    },
    {
     "expr": "process_resident_memory_bytes{node=\"11\"}",
     "legendFormat": "RSS Memory"
    },
    {
     "expr": "rate(process_cpu_seconds_total{node=\"11\"}[15s]) * 100",
     "legendFormat": "CPU usage %"
    }
   ]
  },
  {
   "title": "File Descriptors #11",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 244 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{node=\"11\"}",
     "legendFormat": "Maximum file descriptors"
    },
    {
     "expr": "process_open_fds{node=\"11\"}",
     "legendFormat": "Open file descriptors"
    }
   ]
  },
  {
   "title": "Memory Usage #11",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 244 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nim_gc_mem_bytes{node=\"11\"}",
     "legendFormat": "Nim GC total memory"
    },
    {
     "expr": "nim_gc_mem_occupied_bytes{node=\"11\"}",
     "legendFormat": "Nim GC used memory"
    },
    {
     "expr": "process_resident_memory_bytes{node=\"11\"}",
     "legendFormat": "RSS memory"
    },
    {
     "expr": "process_virtual_memory_bytes{node=\"11\"}",
     "legendFormat": "Virtual memory"
    }
   ]
  },
  {
   "title": "Connected Peers #12",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 252 },
   "targets": [
    {
     "expr": "connected_peers{node=\"12\"}"
    }
   ]
  },
  {
   "title": "Valid Envelopes #12",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 252 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "valid_envelopes_total{node=\"12\"}"
    }
   ]
  },
  {
   "title": "Invalid Envelopes #12",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 252 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "dropped_expired_envelopes_total{node=\"12\"} + dropped_from_future_envelopes_total{node=\"12\"} + dropped_low_pow_envelopes_total{node=\"12\"} + dropped_too_large_envelopes_total{node=\"12\"} + dropped_bloom_filter_mismatch_envelopes_total{node=\"12\"} + dropped_topic_mismatch_envelopes_total{node=\"12\"} +dropped_benign_duplicate_envelopes_total{node=\"12\"} + dropped_duplicate_envelopes_total{node=\"12\"}",
     "legendFormat": "Invalid envelopes"
    }
   ]
  },
  {
   "title": "CPU Usage #12",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 252 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{node=\"12\"}[5s]) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "RSS Memory #12",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 252 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{node=\"12\"}"
    }
   ]
  },
  {
   "title": "Waku Envelopes #12",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 256 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "valid_envelopes_total{node=\"12\"}",
     "legendFormat": "Valid"
    },
    {
     "expr": "dropped_benign_duplicate_envelopes_total{node=\"12\"}",
     "legendFormat": "Benign duplicate"
    },
    {
     "expr": "dropped_duplicate_envelopes_total{node=\"12\"}",
     "legendFormat": "Duplicate"
    },
    {
     "expr": "dropped_expired_envelopes_total{node=\"12\"}",
     "legendFormat": "Expired"
    },
    {
     "expr": "dropped_from_future_envelopes_total{node=\"12\"}",
     "legendFormat": "Future timestamped"
    },
    {
     "expr": "dropped_low_pow_envelopes_total{node=\"12\"}",
     "legendFormat": "Too low PoW"
    },
    {
     "expr": "dropped_bloom_filter_mismatch_envelopes_total{node=\"12\"}",
     "legendFormat": "Bloom filter mismatch"
    },
    {
     "expr": "dropped_topic_mismatch_envelopes_total{node=\"12\"}",
     "legendFormat": "Topic mismatch"
    },
    {
     "expr": "dropped_too_large_envelopes_total{node=\"12\"}",
     "legendFormat": "Too Large"
    },
    {
     "expr": "dropped_full_queue_new_envelopes_total{node=\"12\"}",
     "legendFormat": "Full queue new"
    },
    {
     "expr": "dropped_full_queue_old_envelopes_total{node=\"12\"}",
     "legendFormat": "Full queue old"
    }
   ]
  },
  {
   "title": "Waku Node #12",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 256 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connected_peers{node=\"12\"}",
     "legendFormat": "Connected Peers"
    },
    {
     "expr": "process_resident_memory_bytes{node=\"12\"}",
     "legendFormat": "RSS Memory"
    },
    {
     "expr": "rate(process_cpu_seconds_total{node=\"12\"}[15s]) * 100",
     "legendFormat": "CPU usage %"
    }
   ]
  },
  {
   "title": "File Descriptors #12",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 265 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{node=\"12\"}",
     "legendFormat": "Maximum file descriptors"
    },
    {
     "expr": "process_open_fds{node=\"12\"}",
     "legendFormat": "Open file descriptors"
    }
   ]
  },
  {
   "title": "Memory Usage #12",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 265 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nim_gc_mem_bytes{node=\"12\"}",
     "legendFormat": "Nim GC total memory"
    },
    {
     "expr": "nim_gc_mem_occupied_bytes{node=\"12\"}",
     "legendFormat": "Nim GC used memory"
    },
    {
     "expr": "process_resident_memory_bytes{node=\"12\"}",
     "legendFormat": "RSS memory"
    },
    {
     "expr": "process_virtual_memory_bytes{node=\"12\"}",
     "legendFormat": "Virtual memory"
    }
   ]
  },
  {
   "title": "Connected Peers #13",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 273 },
   "targets": [
    {
     "expr": "connected_peers{node=\"13\"}"
    }
   ]
  },
  {
   "title": "Valid Envelopes #13",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 273 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "valid_envelopes_total{node=\"13\"}"
    }
   ]
  },
  {
   "title": "Invalid Envelopes #13",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 273 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "dropped_expired_envelopes_total{node=\"13\"} + dropped_from_future_envelopes_total{node=\"13\"} + dropped_low_pow_envelopes_total{node=\"13\"} + dropped_too_large_envelopes_total{node=\"13\"} + dropped_bloom_filter_mismatch_envelopes_total{node=\"13\"} + dropped_topic_mismatch_envelopes_total{node=\"13\"} +dropped_benign_duplicate_envelopes_total{node=\"13\"} + dropped_duplicate_envelopes_total{node=\"13\"}",
     "legendFormat": "Invalid envelopes"
    }
   ]
  },
  {
   "title": "CPU Usage #13",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 273 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{node=\"13\"}[5s]) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "RSS Memory #13",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 273 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{node=\"13\"}"
    }
   ]
  },
  {
   "title": "Waku Envelopes #13",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 277 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "valid_envelopes_total{node=\"13\"}",
     "legendFormat": "Valid"
    },
    {
     "expr": "dropped_benign_duplicate_envelopes_total{node=\"13\"}",
     "legendFormat": "Benign duplicate"
    },
    {
     "expr": "dropped_duplicate_envelopes_total{node=\"13\"}",
     "legendFormat": "Duplicate"
    },
    {
     "expr": "dropped_expired_envelopes_total{node=\"13\"}",
     "legendFormat": "Expired"
    },
    {
     "expr": "dropped_from_future_envelopes_total{node=\"13\"}",
     "legendFormat": "Future timestamped"
    },
    {
     "expr": "dropped_low_pow_envelopes_total{node=\"13\"}",
     "legendFormat": "Too low PoW"
    },
    {
     "expr": "dropped_bloom_filter_mismatch_envelopes_total{node=\"13\"}",
     "legendFormat": "Bloom filter mismatch"
    },
    {
     "expr": "dropped_topic_mismatch_envelopes_total{node=\"13\"}",
     "legendFormat": "Topic mismatch"
    },
    {
     "expr": "dropped_too_large_envelopes_total{node=\"13\"}",
     "legendFormat": "Too Large"
    },
    {
     "expr": "dropped_full_queue_new_envelopes_total{node=\"13\"}",
     "legendFormat": "Full queue new"
    },
    {
     "expr": "dropped_full_queue_old_envelopes_total{node=\"13\"}",
     "legendFormat": "Full queue old"
    }
   ]
  },
  {
   "title": "Waku Node #13",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 277 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connected_peers{node=\"13\"}",
     "legendFormat": "Connected Peers"
    },
    {
     "expr": "process_resident_memory_bytes{node=\"13\"}",
     "legendFormat": "RSS Memory"
    },
    {
     "expr": "rate(process_cpu_seconds_total{node=\"13\"}[15s]) * 100",
     "legendFormat": "CPU usage %"
    }
   ]
  },
  {
   "title": "File Descriptors #13",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 286 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{node=\"13\"}",
     "legendFormat": "Maximum file descriptors"
    },
    {
     "expr": "process_open_fds{node=\"13\"}",
     "legendFormat": "Open file descriptors"
    }
   ]
  },
  {
   "title": "Memory Usage #13",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 286 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nim_gc_mem_bytes{node=\"13\"}",
     "legendFormat": "Nim GC total memory"
    },
    {
     "expr": "nim_gc_mem_occupied_bytes{node=\"13\"}",
     "legendFormat": "Nim GC used memory"
    },
    {
     "expr": "process_resident_memory_bytes{node=\"13\"}",
     "legendFormat": "RSS memory"
    },
    {
     "expr": "process_virtual_memory_bytes{node=\"13\"}",
     "legendFormat": "Virtual memory"
    }
   ]
  }
 ]
}