global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "Monitoring"

scrape_configs:
  - job_name: "liteprotocoltester"
    static_configs:
    - targets: ["lightpush-service:8003",
                "filter-service:8003",
                "liteprotocoltester-publishernode-1:8003",
                "liteprotocoltester-publishernode-2:8003",
                "liteprotocoltester-publishernode-3:8003",
                "liteprotocoltester-publishernode-4:8003",
                "liteprotocoltester-publishernode-5:8003",
                "liteprotocoltester-publishernode-6:8003",
                "receivernode:8003"]
