version: "1.1" #config version

tag:
    pattern: "v%d.%d.%d"
    filter: "v*"

release-notes:
    sections: # Array with each section of release note. Check template section for more information.
        - name: Features # Name used on section.
          section-type: commits # Type of the section, supported types: commits, breaking-changes.
          commit-types: [feat] # Commit types for commit section-type, one commit type cannot be in more than one section.
        - name: Bug Fixes
          section-type: commits
          commit-types: [fix, bug]
        - name: Changes
          section-type: commits
          commit-types: [chore, docs, build, refactor, docker]

commit-message:

    issue:
      regex: '#[0-9]+' # Regex for issue id.