openapi: 3.0.3
info:
  title: Waku V2 node REST API
  version: 1.0.0
  contact:
    name: VAC Team
    url: https://forum.vac.dev/

tags:
  - name: debug
    description: Debug REST API for WakuV2 node

paths:
  /debug/v1/info:
    get:
      summary: Get node info
      description: Retrieve information about a Waku v2 node.
      operationId: getNodeInfo
      tags:
        - debug
      responses:
        '200':
          description: Information about a Waku v2 node.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WakuInfo'
        '4XX':
          description: Bad request error.
        '5XX':
          description: Unexpected error.

  /debug/v1/version:
    get:
      summary: Get node version
      description: Retrieve the Waku v2 node version.
      operationId: getNodeVersion
      tags:
        - debug
      responses:
        '200':
          description: The version of a Waku v2 node.
          content:
            text/plain:
              schema:
                type: string
        '4XX':
          description: Bad request error.
        '5XX':
          description: Unexpected error.

components:
  schemas:
    WakuInfo:
      type: object
      properties:
        listenAddresses:
          type: array
          items:
            type: string
        enrUri:
          type: string
      required:
        - listenAddresses
