{.push raises: [Defect].}

import 
  options, chronos, stint,
  web3,
  eth/keys

## Bn256 and RLN are Nim wrappers for the data types used in 
## the rln library https://github.com/kilic/rln/blob/3bbec368a4adc68cd5f9bfae80b17e1bbb4ef373/src/ffi.rs
type Bn256* = pointer
type RLN*[E] = pointer


type IDKey* = array[32, byte]
type IDCommitment* = array[32, byte]
# represents a Merkle tree node which is the output of 
# Poseidon hash function implemented by rln lib
type MerkleNode* = array[32,byte] 

# Custom data types defined for waku rln relay -------------------------
type MembershipKeyPair* = object 
  # node's identity key (a secret key) which is selected randomly
  idKey*: IDKey 
  # hash of node's identity key generated by 
  # Poseidon hash function implemented in rln lib
  idCommitment*: IDCommitment 

type WakuRLNRelay* = object 
  membershipKeyPair*: MembershipKeyPair
  membershipIndex*: uint # index of peers in the Merkle tree
  membershipContractAddress*: Address
  ethClientAddress*: string
  ethAccountAddress*: Address
  # this field is required for signing transactions
  # TODO may need to erase this ethAccountPrivateKey when is not used
  # TODO may need to make ethAccountPrivateKey mandatory
  ethAccountPrivateKey*: Option[PrivateKey]
  rlnInstance*: RLN[Bn256]
  

# inputs of the membership contract constructor
# TODO may be able to make these constants private and put them inside the waku_rln_relay_utils
const 
  MembershipFee* = 5.u256
  Depth* = 32.u256
  # TODO the EthClient should be an input to the rln-relay
  EthClient* = "ws://localhost:8540/"