openapi: 3.0.3
info:
  title: Waku V2 node REST API
  version: 1.0.0
  contact:
    name: VAC Team
    url: https://forum.vac.dev/

tags:
  - name: lightpush
    description: Lightpush REST API for WakuV2 node

paths:
  /lightpush/v1/message:
    post:
      summary: Request a message relay from a LightPush service provider
      description: Push a message to be relayed on a PubSub topic.
      operationId: postMessagesToPubsubTopic
      tags:
        - lightpush
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PushRequest'
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: Bad request.
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
        '503':
          description: Service not available
          content:
            text/plain:
              schema:
                type: string

components:
  schemas:
    PubsubTopic:
      type: string

    ContentTopic:
      type: string

    WakuMessage:
      type: object
      properties:
        payload:
          type: string
          format: byte
        contentTopic:
          $ref: '#/components/schemas/ContentTopic'
        version:
          type: number
        timestamp:
          type: number
      required:
        - payload
        - contentTopic

    PushRequest:
      type: object
      properties:
        pubsubTopic:
          $ref: '#/components/schemas/PubsubTopic'
        message:
          $ref: '#/components/schemas/WakuMessage'
      required:
        - message
