{
 "title": "sonda-monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "label": "node", "query": { "query": "label_values(node)" } }
  ]
 },
 "panels": [
  {
   "title": "Sent Sonda Messages",
   "type": "timeseries",
   "description": "Sonda messages successfully sent to the network",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "successful_sonda_msgs_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Failed Sonda Messages",
   "type": "timeseries",
   "description": "Sonda messages that failed to be sent to the network",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "failed_sonda_msgs_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Sent Sonda Messages Rate per Minute",
   "type": "timeseries",
   "description": "Sonda messages successfully sent to the network",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(successful_sonda_msgs_total[5m])/5",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Sonda Messages per Minute",
   "type": "timeseries",
   "description": "Sonda messages that failed to be sent to the network",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "increase(failed_sonda_msgs_total[5m]) / 5",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Store Responses",
   "type": "timeseries",
   "description": "Store responses including the latest Sonda message ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "successful_store_queries_total{node=~\"^$node$\"}",
     "legendFormat": "{__name__=\"{{__name__}}\" , node=\"{{node}}\"}"
    }
   ]
  },
  {
   "title": "Failed Store Queries",
   "type": "timeseries",
   "description": "Store queries with a non-200 response",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "failed_store_queries_total{node=~\"^$node$\"}",
     "legendFormat": "{__name__=\"{{__name__}}\" , error=\"{{error}}\", node=\"{{node}}\"}"
    }
   ]
  },
  {
   "title": "Successful Store Responses per Minute",
   "type": "timeseries",
   "description": "Store responses including the latest Sonda message ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "increase(successful_store_queries_total{node=~\"^$node$\"}[5m]) / 5",
     "legendFormat": "{__name__=\"{{__name__}}\" , node=\"{{node}}\"}"
    }
   ]
  },
  {
   "title": "Failed Store Queries per Minute",
   "type": "timeseries",
   "description": "Store queries with a non-200 response",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "increase(failed_store_queries_total{node=~\"^$node$\"}[5m]) / 5",
     "legendFormat": "{__name__=\"{{__name__}}\" , error=\"{{error}}\", node=\"{{node}}\"}"
    }
   ]
  },
  {
   "title": "Empty Store Responses",
   "type": "timeseries",
   "description": "Store responses that didn't include our latest Sonda message",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "empty_store_responses_total{node=~\"^$node$\"}",
     "legendFormat": "{__name__=\"{{__name__}}\" , node=\"{{node}}\"}"
    }
   ]
  },
  {
   "title": "Empty Store Responses per Minute",
   "type": "timeseries",
   "description": "Store responses that didn't include our latest Sonda message",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "increase(empty_store_responses_total{node=~\"^$node$\"}[5m]) / 5",
     "legendFormat": "{__name__=\"{{__name__}}\" , node=\"{{node}}\"}"
    }
   ]
  },
  {
   "title": "Store Query Latency (seconds)",
   "type": "histogram",
   "description": "Latency of store queries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "store_query_latency{node=~\"^$node$\"}",
     "legendFormat": "{__name__=\"{{__name__}}\" , node=\"{{node}}\"}"
    }
   ]
  },
  {
   "title": "Store Query Latency (seconds)",
   "type": "timeseries",
   "description": "Latency of each store query",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "store_query_latency{node=~\"^$node$\"}",
     "legendFormat": "{__name__=\"{{__name__}}\" , node=\"{{node}}\"}"
    }
   ]
  },
  {
   "title": "Node health",
   "type": "timeseries",
   "description": "Node health according to the configured health threshold. 1 means healthy, 0 not.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "node_health{node=~\"^$node$\"}",
     "legendFormat": "{__name__=\"{{__name__}}\" , node=\"{{node}}\"}"
    }
   ]
  }
 ]
}