# Incentivization PoC: Charlie

# Charlie is an isolated node with Relay and Lightpush enabled.
# Charlie fails to fulfill Alice's request due to lack of peers.
# However, Charlie implements eligibility-related checks,
# and rejects Alice's ineligible requests before trying to fulfil them.

# Enable Lightpush
lightpush = true

# Use a pre-generated static node key for reproducibility
nodekey = "fbfa8c3e38e7594500e9718b8c800e2d1a3ef5bc65ce041adf788d276035230f"

# Enable Relay (required for eligibility module)
relay = true

# Connect to The Waku Network (TWN)
preset = "twn"

# Disable discovery methods to ensure node isolation
discv5-discovery = false
dns-discovery = false

# Eligibility-related parameters
eligibility-enabled = true
eligibility-receiver-address = "0x6298cc1831B6E5eDEDA5cC73bc75a040108358Bb"
eligibility-payment-amount-wei = 1000000000

# Shift ports to avoid conflicts in local setups
ports-shift = 3

# RLN-related parameters
rln-relay-tree-path = "~/.waku/rln-tree-db-3"

# NAT (required for local setup: TODO: explain why)
nat = "upnp"

# Enable REST API including admin functions
rest = true
rest-admin = true
rest-address = "127.0.0.1"
rest-allow-origin = [ "*" ]

# Log level
log-level = "DEBUG"

# CLI-only equivalent command (for reference)
# ./build/wakunode2 --lightpush --rln-relay-tree-path=~/.waku/rln-tree-db-3 --nodekey=$CHARLIE_NODEKEY --discv5-discovery=false --dns-discovery=false --rest=true --rest-admin=true --rest-address=127.0.0.1 --ports-shift=3 --rest-allow-origin="*" --preset=twn --relay=true --nat=upnp --rln-relay-eth-client-address=$RLN_RELAY_ETH_CLIENT_ADDRESS --rln-relay-cred-password=$RLN_RELAY_CRED_PASSWORD --rln-relay-cred-path=$RLN_RELAY_CRED_PATH --log-level=DEBUG --eligibility-enabled=true --eligibility-eth-client-address=$ELIGIBILITY_ETH_CLIENT_ADDRESS --eligibility-receiver-address=$ELIGIBILITY_RECEIVER_ADDRESS --eligibility-payment-amount-wei=$ELIGIBILITY_PAYMENT_AMOUNT_WEI