log-level = "INFO"
relay = true
mix = true
filter = true
store = false
lightpush = true
max-connections = 150
peer-exchange = true
metrics-logging = false
cluster-id = 2
discv5-discovery = true
discv5-udp-port = 9002
discv5-enr-auto-update = true
discv5-bootstrap-node = ["enr:-Nq4QHkkKSYWg12nFHlB-Yjb53I922uquTL26R7G6Kk7Z0gNJx2N4qCt_fq0RFg-_ZDX5ju8SatMjNYyImPprl37utMEgmlkgnY0gmlwhH8AAAGHbWl4LWtleaCdCc5iT3bo9gYmXtucyit96bQXcqbXhL3a-S_6j7p9LIptdWx0aWFkZHJzigAIBMCoAWkG6mGCcnOFAAIBAACJc2VjcDI1NmsxoQOkRbVSVQYdEmDqD_Ma4J10paYhQEZkJBfXfEZ-H0noqIN0Y3CC6mGDdWRwgiMphXdha3UyLQ"]
rest = false
rest-admin = false
ports-shift = 3
num-shards-in-network = 1
shard = [0]
agent-string = "nwaku-mix"
nodekey = "ed54db994682e857d77cd6fb81be697382dc43aa5cd78e16b0ec8098549f860e"
mixkey = "b858ac16bbb551c4b2973313b1c8c8f7ea469fca03f1608d200bbf58d388ec7f"
rendezvous = true
listen-address = "127.0.0.1"
nat = "extip:127.0.0.1"
ip-colocation-limit=0
#staticnode = ["/ip4/127.0.0.1/tcp/60001/p2p/16Uiu2HAmPiEs2ozjjJF2iN2Pe2FYeMC9w4caRHKYdLdAfjgbWM6o", "/ip4/127.0.0.1/tcp/60002/p2p/16Uiu2HAmLtKaFaSWDohToWhWUZFLtqzYZGPFuXwKrojFVF6az5UF","/ip4/127.0.0.1/tcp/60004/p2p/16Uiu2HAmPwRKZajXtfb1Qsv45VVfRZgK3ENdfmnqzSrVm3BczF6f","/ip4/127.0.0.1/tcp/60005/p2p/16Uiu2HAmRhxmCHBYdXt1RibXrjAUNJbduAhzaTHwFCZT4qWnqZAu"]
