import
  ./test_base64_codec,
  ./test_confutils_envvar,
  ./test_enr_builder,
  ./test_envvar_serialization,
  ./test_protobuf_validation,
  ./test_sqlite_migrations,
  ./test_parse_size,
  ./test_tokenbucket,
  ./test_requestratelimiter,
  ./test_timed_map
