# Incentivization PoC: Charlie

# Charlie is an isolated node with Relay and Lightpush enabled.
# Charlie fails to fulfill Alice's request due to lack of peers.
# However, Charlie implements eligibility-related checks,
# and rejects Alice's ineligible requests before trying to fulfil them.

# Enable Lightpush
lightpush = true

# Use a pre-generated static node key for reproducibility
nodekey = "fbfa8c3e38e7594500e9718b8c800e2d1a3ef5bc65ce041adf788d276035230f"

# Enable Relay (required for eligibility module)
relay = true

# Connect to The Waku Network (TWN)
preset = "twn"

# Disable discovery methods to ensure node isolation
discv5-discovery = false
dns-discovery = false
nat = "upnp"

# Eligibility-related parameters
eligibility-enabled = true
eligibility-receiver-address = "0x6298cc1831B6E5eDEDA5cC73bc75a040108358Bb"
eligibility-payment-amount-wei = 1000000000

# Shift ports to avoid conflicts in local setups
ports-shift = 3

# RLN-related parameters
rln-relay-tree-path = "~/.waku/rln-tree-db-3"

# Enable REST API including admin functions
rest = true
rest-admin = true
rest-address = "127.0.0.1"
rest-allow-origin = [ "127.0.0.1:*" ]

# Log level
log-level = "DEBUG"
