/* Generated by Nim Compiler v1.6.11 */
#ifndef __libwaku__
#define __libwaku__
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef N_CDECL_PTR(void, tyProc__5cp59bim9aJ4WupX5aVaD1Sg) (NCSTRING signal_0);
struct TGenericSeq {NI len;
NI reserved;
};
struct NimStringDesc {  TGenericSeq Sup;NIM_CHAR data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NOCONV(void, signalHandler)(int sign);
N_LIB_PRIVATE N_NIMCALL(NI, getRefcount)(void* p);
N_LIB_IMPORT N_CDECL(NCSTRING, waku_version)(void);
N_LIB_IMPORT N_CDECL(void, waku_set_event_callback)(tyProc__5cp59bim9aJ4WupX5aVaD1Sg callback);
N_LIB_IMPORT N_CDECL(void, waku_content_topic)(NCSTRING appName, NU appVersion, NCSTRING contentTopicName, NCSTRING encoding, NimStringDesc** outContentTopic);
N_LIB_IMPORT N_CDECL(void, waku_pubsub_topic)(NCSTRING topicName, NCSTRING encoding, NimStringDesc** outPubsubTopic);
N_LIB_IMPORT N_CDECL(void, waku_default_pubsub_topic)(NimStringDesc** defPubsubTopic);
N_LIB_IMPORT N_CDECL(void, waku_relay_publish)(NCSTRING pubSubTopic, NCSTRING jsonWakuMessage, NI timeoutMs, NimStringDesc** jsonResp);
N_LIB_IMPORT N_CDECL(void, waku_new)(NCSTRING config_file);
N_LIB_IMPORT N_CDECL(void, waku_start)(void);
N_LIB_IMPORT N_CDECL(void, waku_relay_subscribe)(NCSTRING pubSubTopic, NimStringDesc** jsonResp);
N_LIB_IMPORT N_CDECL(void, waku_relay_unsubscribe)(NCSTRING pubSubTopic, NimStringDesc** jsonResp);
N_CDECL(void, NimMain)(void);
#endif /* __libwaku__ */
