name: test2

on:
  pull_request:
    paths:
      - 'waku/v1/**'
      - 'tests/all_tests_v1.nim'
      - 'tests/v1/**'

      - 'waku/whisper/**'
      - 'tests/whisper/**'
      - 'tests/all_tests_whisper.nim'

      - 'ci/**'
      - 'metrics/**'
      - 'docs/**'
      - '**.md'
  push:
    branches:
      - master
    paths:
      - 'ci/**'
      - 'metrics/**'
      - 'docs/**'
      - '**.md'

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    name: ${{ github.workflow }}-${{ matrix.platform }}
    steps:
      - run: 'echo "No test required"'
