{
 "title": "Waku Node2",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Waku Peers #0",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "libp2p_pubsub_peers{instance=\"localhost:8008\",job=\"waku\"}",
     "legendFormat": "LibP2P PubSub Peers"
    },
    {
     "expr": "waku_filter_peers{instance=\"localhost:8008\",job=\"waku\"}",
     "legendFormat": "Filter Peers"
    },
    {
     "expr": "waku_store_peers{instance=\"localhost:8008\",job=\"waku\"}",
     "legendFormat": "Store Peers"
    },
    {
     "expr": "waku_swap_peers{instance=\"localhost:8008\",job=\"waku\"}",
     "legendFormat": "Swap Peers"
    }
   ]
  },
  {
   "title": "CPU Usage #0",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"localhost:8008\",job=\"waku\"}[5s]) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "RSS Memory #0",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"localhost:8008\",job=\"waku\"}"
    }
   ]
  },
  {
   "title": "Waku Messages #0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "waku_node_messages_total{instance=\"localhost:8008\",job=\"waku\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "waku_store_messages{instance=\"localhost:8008\",job=\"waku\"}",
     "legendFormat": "store"
    }
   ]
  },
  {
   "title": "Waku Peers #0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libp2p_pubsub_peers{instance=\"localhost:8008\",job=\"waku\"}",
     "legendFormat": "LibP2P PubSub Peers"
    },
    {
     "expr": "waku_filter_peers{instance=\"localhost:8008\",job=\"waku\"}",
     "legendFormat": "Filter Peers"
    },
    {
     "expr": "waku_store_peers{instance=\"localhost:8008\",job=\"waku\"}",
     "legendFormat": "Store Peers"
    },
    {
     "expr": "waku_swap_peers{instance=\"localhost:8008\",job=\"waku\"}",
     "legendFormat": "Swap Peers"
    }
   ]
  },
  {
   "title": "Waku Errors #0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "waku_node_errors{instance=\"localhost:8008\",job=\"waku\"}",
     "legendFormat": "Node: {{type}}"
    },
    {
     "expr": "waku_filter_errors{instance=\"localhost:8008\",job=\"waku\"}",
     "legendFormat": "Filter: {{type}}"
    },
    {
     "expr": "waku_store_errors{instance=\"localhost:8008\",job=\"waku\"}",
     "legendFormat": "Store: {{type}}"
    },
    {
     "expr": "waku_swap_errors{instance=\"localhost:8008\",job=\"waku\"}",
     "legendFormat": "Swap: {{type}}"
    }
   ]
  },
  {
   "title": "Waku Node #0",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{ninstance=\"localhost:8008\",job=\"waku\"} / (1024 * 1024)",
     "legendFormat": "RSS Memory (MB)"
    },
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"localhost:8008\",job=\"waku\"}[15s]) * 100",
     "legendFormat": "CPU usage %"
    }
   ]
  },
  {
   "title": "Memory Usage #0",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nim_gc_mem_bytes{instance=\"localhost:8008\",job=\"waku\"}",
     "legendFormat": "Nim GC total memory"
    },
    {
     "expr": "nim_gc_mem_occupied_bytes{instance=\"localhost:8008\",job=\"waku\"}",
     "legendFormat": "Nim GC used memory"
    },
    {
     "expr": "process_resident_memory_bytes{instance=\"localhost:8008\",job=\"waku\"}",
     "legendFormat": "RSS memory"
    },
    {
     "expr": "process_virtual_memory_bytes{instance=\"localhost:8008\",job=\"waku\"}",
     "legendFormat": "Virtual memory"
    }
   ]
  },
  {
   "title": "File Descriptors #0",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{instance=\"localhost:8008\",job=\"waku\"}",
     "legendFormat": "Maximum file descriptors"
    },
    {
     "expr": "process_open_fds{instance=\"localhost:8008\",job=\"waku\"}",
     "legendFormat": "Open file descriptors"
    }
   ]
  }
 ]
}